---
title: "Assignment 1"
author: "SID: 490300286"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: cosmo
    toc: true
    toc_float: true
    number_sections: false
    fig_caption: yes
    code_folding: hide
bibliography: references.bib  
nocite: | 
  @tidyverse, @DT, @naniar, @R
---

```{r message = F, warning  = F, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)     # new tidy functions
library(naniar)

load("tech_data.Rdata")
```

```{r}
dat = tech_biom

# Recoding all EXL vars as numeric (they are fct initally)
dat$EXLWTBC = as.numeric(levels(tech_biom$EXLWTBC))[tech_biom$EXLWTBC] 
dat$EXLWMBC = as.numeric(levels(tech_biom$EXLWMBC))[tech_biom$EXLWMBC]
dat$EXLWVBC = as.numeric(levels(tech_biom$EXLWVBC))[tech_biom$EXLWVBC]

# recoding 9999 or 9996 in EXL[XXXX] cols as NA
dat = dat %>% replace_with_na_at(.vars = c("EXLWTBC",
                                            "EXLWMBC",
                                            "EXLWVBC"),
                     condition = ~.x %in% c(9999,
                                            9996))

# adding in 0 where they were erroneously removed from ADTOTSE and SLPTIME vars

for (i in 1:nrow(dat)) {
  if (dat$ADTOTSE_MISS[i] == "did not sit or lie for sedentary activities in the last week") {
    dat$ADTOTSE[i] = 0
  }
  if (dat$SLPTIME_MISS[i] == "did not go to bed") {
    dat$SLPTIME[i] = 0
  }
}


# removing rows where EXLWVBC + EXLWMBC <= EXLWTBC
dat = dat %>% filter(EXLWVBC + EXLWMBC <= EXLWTBC |
                         is.na(EXLWVBC) | 
                         is.na(EXLWMBC) |
                         is.na(EXLWTBC))


# link nutrient data with biomedical data

macros = tech_nutr %>% select(ABSPID,
                              PROTT1,
                              PROTT2,
                              FATT1,
                              FATT2,
                              CHOWSAT1,
                              CHOWSAT2)


# gettin average of macros
macros$avg_protein <- rowMeans(macros[ , c(2,3)], na.rm=TRUE)
macros$avg_fat <- rowMeans(macros[ , c(4,5)], na.rm=TRUE)
macros$avg_carb <- rowMeans(macros[ , c(6,7)], na.rm=TRUE)

# making macros1 only df of averages
macros1 = macros %>% select(-c(2:7))

# trying to find % of each macro

macros2$pct_protein <- NA
macros2$pct_fat <- NA
macros2$pct_carb <- NA

for (i in 1:nrow(macros2)) {
  macros2$pct_protein[i] <- macros2$avg_protein[i]/rowSums(macros2[,c(2:4)])[i]
  macros2$pct_fat[i] <- macros2$avg_fat[i]/rowSums(macros2[,c(2:4)])[i]
  macros2$pct_carb[i] <- macros2$avg_carb[i]/rowSums(macros2[,c(2:4)])[i]
}


pct_macros_numeric = macros2

pct_macros_numeric = macros2 %>% 
  select(-c(2:4))

pct_macros_numeric = na.omit(pct_macros_numeric)


```

# Produce complete dataset

```{r}
dat1 = dat %>% select(c(1:53))
final <- merge(dat1, pct_macros_numeric, by = "ABSPID")

final_with_vars <- final %>% select(ABSPID,
                                    BMISC,
                                    AGEC,
                                    SEX,
                                    pct_protein,
                                    pct_carb,
                                    pct_fat
                                    )


final_with_vars = final_with_vars %>% na.omit()
```


# Correlation matrix of vars

```{r}
library(corrplot)
library(GGally)

numerics <- final_with_vars %>% select(BMISC,
                                       AGEC,
                                       pct_protein,
                                       pct_carb,
                                       pct_fat)

ggpairs(numerics)
```



```{r}
df <- final_with_vars %>% select(-ABSPID)
lm1 <- lm(BMISC ~ ., data = df)

summary(lm1)
```





